version: "3"

services:
  blog-in-golang:
    image: blog:latest
    container_name: blog-in-golang
    restart: unless-stopped
    ports:
      - "443:443/tcp"
      - "80:80/tcp"
    volumes:
      - '/home/metzel/containers/blog-in-golang/certmagic:/root/.local/share/certmagic'
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      ARTICLES: "Live-Articles"
      DEPLOYMENT: "GCP"
      DOMAIN: "gcp.mitchelletzel.com"