version: "3"

services:
  blog-in-golang-develop:
    image: blog:develop
    container_name: blog-in-golang-develop
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "85:8080/tcp"
    volumes:
      - '/share/Container/blog-in-golang:/config'
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      ARTICLES: "Test-Articles"