version: "3"

services:
  github-runner:
    image: github-runner:latest
    container_name: github-runner
    restart: unless-stopped
    privileged: true
    environment:
      REPO: "etzelm/blog-in-golang"
      TOKEN: "${GITHUB_TOKEN}"