name: blog-in-golang-gcp
# This workflow deploys blog changes to my GCP VM
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:

  GCP-deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: [self-hosted, Linux, X64, gcp]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        shell: bash
        run: |
          echo STARTING BUILD
          BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "BRANCH: $BRANCH"
          if [[ $BRANCH == "master" ]]; then TAG="latest"; else TAG="$BRANCH"; fi
          echo "TAG: $TAG"
          pushd realtor
          npm install
          yarn build
          popd
          docker build -t blog:$TAG .
          docker system prune -f