name: blog-in-golang-nas
# This workflow deploys blog changes to my NAS
on:
  push:
    branches:
      - 'develop'
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:

  NAS-build:
    if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/develop'
    runs-on: [self-hosted, Linux, X64, nas]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        shell: bash
        run: |
          echo STARTING BUILD
          BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "BRANCH: $BRANCH"
          pushd realtor
          npm install
          yarn build
          popd
          go mod download
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o blog-in-golang .

  NAS-tests:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
    runs-on: [self-hosted, Linux, X64, nas]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Tests
        shell: bash
        run: |
          echo RUNNING TESTS TO CACHE CLOUDFRONT CONTENT
          while IFS= read -r line
          do
            echo $line
            curl "$line" > /dev/null
          done < .github/workflows/urls.txt