name: NAS-dev-push
# This workflow deploys develop branch blog changes to my NAS
on:
  push:
    branches:
      - 'develop'
  pull_request:
  workflow_dispatch:

jobs:

  build:
    runs-on: [self-hosted, Linux, X64, nas]
    env:
        NAS_ADDR: ${{ secrets.NAS_ADDR }}
        NAS_USER: ${{ secrets.NAS_USER }}
        NAS_PASS: ${{ secrets.NAS_PASS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check
        shell: bash
        run: |
          echo TESTING OUTPUT
          echo "The TEST is: ${TEST} or $TEST or "
          echo $TEST
          printenv
